import type { Express } from "express";
import { createServer, type Server } from "http";

const DEPENDENCY_DATA = {
  projectInfo: {
    groupId: "com.projectgoth",
    artifactId: "Fusion",
    oldVersion: "8.75.132",
    newVersion: "9.0.0",
    oldJava: "1.5 / 1.6",
    newJava: "21 (LTS)",
    oldSpring: "2.5.5",
    newSpring: "Spring Boot 3.3.1",
    buildSystem: "Maven",
    scm: "SVN → Git",
  },
  summary: {
    totalDependencies: 42,
    updated: 28,
    removed: 9,
    added: 5,
    securityFixes: 4,
    majorUpgrades: 14,
    minorUpgrades: 14,
  },
  dependencies: [
    {
      id: 1,
      category: "Logging",
      name: "Log4j",
      oldCoord: "log4j:log4j:1.2.9",
      newCoord: "ch.qos.logback:logback-classic (via SLF4J)",
      oldVersion: "1.2.9",
      newVersion: "SLF4J 2.x + Logback 1.5.x",
      status: "critical",
      reason: "CVE-2019-17571 – remote code execution. Replaced with Logback + SLF4J bridge.",
      breaking: true,
      cveIds: ["CVE-2019-17571"],
    },
    {
      id: 2,
      category: "Logging",
      name: "Log4j-over-SLF4J bridge",
      oldCoord: "(not present)",
      newCoord: "org.slf4j:log4j-over-slf4j",
      oldVersion: "—",
      newVersion: "2.0.13",
      status: "added",
      reason: "Allows legacy log4j API calls to route through SLF4J without code changes.",
      breaking: false,
      cveIds: [],
    },
    {
      id: 3,
      category: "Cloud",
      name: "AWS SDK",
      oldCoord: "com.amazonaws:aws-java-sdk:1.3.20",
      newCoord: "software.amazon.awssdk:s3,ses (BOM 2.26.0)",
      oldVersion: "1.3.20",
      newVersion: "2.26.0",
      status: "major",
      reason: "SDK v1 is end-of-life. v2 is async-first, modular, and actively maintained.",
      breaking: true,
      cveIds: [],
    },
    {
      id: 4,
      category: "Database",
      name: "MySQL Connector",
      oldCoord: "mysql:mysql-connector-java:5.1.7",
      newCoord: "com.mysql:mysql-connector-j:8.4.0",
      oldVersion: "5.1.7",
      newVersion: "8.4.0",
      status: "major",
      reason: "New Maven coordinates, MySQL 8 protocol support, timezone fixes.",
      breaking: true,
      cveIds: [],
    },
    {
      id: 5,
      category: "Database",
      name: "c3p0 Connection Pool",
      oldCoord: "c3p0:c3p0:0.9.1.2",
      newCoord: "com.mchange:c3p0:0.10.1 + HikariCP (primary)",
      oldVersion: "0.9.1.2",
      newVersion: "0.10.1 + HikariCP",
      status: "major",
      reason: "HikariCP is now primary pool for Spring Boot. c3p0 retained for legacy modules.",
      breaking: false,
      cveIds: [],
    },
    {
      id: 6,
      category: "Database",
      name: "Commons DBCP",
      oldCoord: "commons-dbcp:commons-dbcp:1.2.2",
      newCoord: "→ HikariCP (via Spring Boot)",
      oldVersion: "1.2.2",
      newVersion: "Removed",
      status: "removed",
      reason: "Superseded by HikariCP which is the Spring Boot 3 default connection pool.",
      breaking: false,
      cveIds: [],
    },
    {
      id: 7,
      category: "Cache",
      name: "Ehcache",
      oldCoord: "net.sf.ehcache:ehcache:1.6.1",
      newCoord: "org.ehcache:ehcache:3.10.8",
      oldVersion: "1.6.1",
      newVersion: "3.10.8",
      status: "major",
      reason: "Complete rewrite; new XML config format, JCache (JSR-107) compatible.",
      breaking: true,
      cveIds: [],
    },
    {
      id: 8,
      category: "Cache",
      name: "Memcached Client",
      oldCoord: "com.danga:java_memcached-release:2.0.1",
      newCoord: "net.spy:spymemcached:2.12.3",
      oldVersion: "2.0.1",
      newVersion: "2.12.3",
      status: "major",
      reason: "Old Danga client is unmaintained and unavailable on Maven Central.",
      breaking: true,
      cveIds: [],
    },
    {
      id: 9,
      category: "Redis",
      name: "Jedis",
      oldCoord: "redis.clients:jedis:2.5.2",
      newCoord: "redis.clients:jedis:5.1.3",
      oldVersion: "2.5.2",
      newVersion: "5.1.3",
      status: "major",
      reason: "Java 8+ baseline, SSL/TLS, cluster mode support, unified pool.",
      breaking: true,
      cveIds: [],
    },
    {
      id: 10,
      category: "Redis",
      name: "Commons Pool2",
      oldCoord: "org.apache.commons:commons-pool2:2.2",
      newCoord: "org.apache.commons:commons-pool2:2.12.0",
      oldVersion: "2.2",
      newVersion: "2.12.0",
      status: "minor",
      reason: "Security patches and performance improvements.",
      breaking: false,
      cveIds: [],
    },
    {
      id: 11,
      category: "Framework",
      name: "Spring Framework",
      oldCoord: "org.springframework:spring:2.5.5",
      newCoord: "org.springframework.boot:spring-boot-starter-parent:3.3.1",
      oldVersion: "2.5.5",
      newVersion: "Boot 3.3.1 (Spring 6.1.x)",
      status: "critical",
      reason: "10+ year old version; no security patches. Boot 3 requires Jakarta EE 10 namespace migration.",
      breaking: true,
      cveIds: [],
    },
    {
      id: 12,
      category: "Framework",
      name: "JBoss EJB Client",
      oldCoord: "org.jboss:jbossall-client:4.0.1",
      newCoord: "→ Removed (use Spring CDI / @Service beans)",
      oldVersion: "4.0.1",
      newVersion: "Removed",
      status: "removed",
      reason: "EJB 2.0 container-managed beans replaced by Spring-managed @Service components.",
      breaking: true,
      cveIds: [],
    },
    {
      id: 13,
      category: "API",
      name: "JAX-RS API (RESTEasy)",
      oldCoord: "org.jboss.resteasy:jaxrs-api:2.0.1.GA",
      newCoord: "jakarta.ws.rs:jakarta.ws.rs-api:4.0.0",
      oldVersion: "2.0.1.GA",
      newVersion: "4.0.0",
      status: "major",
      reason: "javax.ws.rs → jakarta.ws.rs namespace migration for Jakarta EE 10.",
      breaking: true,
      cveIds: [],
    },
    {
      id: 14,
      category: "API",
      name: "RESTEasy",
      oldCoord: "org.jboss.resteasy:resteasy-jaxrs:2.0.1.GA",
      newCoord: "org.jboss.resteasy:resteasy-core:6.2.9.Final",
      oldVersion: "2.0.1.GA",
      newVersion: "6.2.9.Final",
      status: "major",
      reason: "Jakarta EE 10 compatible; full Jakarta namespace.",
      breaking: true,
      cveIds: [],
    },
    {
      id: 15,
      category: "API",
      name: "Servlet API",
      oldCoord: "javax.servlet:servlet-api:2.4",
      newCoord: "jakarta.servlet:jakarta.servlet-api:6.1.0",
      oldVersion: "2.4",
      newVersion: "6.1.0",
      status: "critical",
      reason: "javax → jakarta package rename. All import statements must be updated.",
      breaking: true,
      cveIds: [],
    },
    {
      id: 16,
      category: "API",
      name: "JavaMail",
      oldCoord: "javax.mail:mail:1.3.1",
      newCoord: "jakarta.mail:jakarta.mail-api:2.1.3",
      oldVersion: "1.3.1",
      newVersion: "2.1.3",
      status: "major",
      reason: "Jakarta Mail 2.x under eclipse-ee4j; javax → jakarta namespace.",
      breaking: true,
      cveIds: [],
    },
    {
      id: 17,
      category: "API",
      name: "JAXB",
      oldCoord: "javax.xml.bind:jaxb-api:2.1",
      newCoord: "jakarta.xml.bind:jakarta.xml.bind-api:4.0.2",
      oldVersion: "2.1",
      newVersion: "4.0.2",
      status: "major",
      reason: "Removed from JDK in Java 11; must add as explicit dependency.",
      breaking: true,
      cveIds: [],
    },
    {
      id: 18,
      category: "JSON",
      name: "Jackson",
      oldCoord: "com.fasterxml.jackson.core:jackson-core:2.1.5",
      newCoord: "com.fasterxml.jackson.core:jackson-core:2.17.x (BOM)",
      oldVersion: "2.1.5",
      newVersion: "2.17.x",
      status: "minor",
      reason: "Many CVE fixes, Java records support, performance improvements.",
      breaking: false,
      cveIds: ["CVE-2019-14379", "CVE-2020-8840"],
    },
    {
      id: 19,
      category: "JSON",
      name: "Codehaus Jackson (legacy)",
      oldCoord: "org.codehaus.jackson:jackson-mapper-asl:1.8.9",
      newCoord: "→ Removed (use com.fasterxml.jackson instead)",
      oldVersion: "1.8.9",
      newVersion: "Removed",
      status: "removed",
      reason: "org.codehaus.jackson is unmaintained since 2013. Migrate to com.fasterxml.jackson.",
      breaking: true,
      cveIds: ["CVE-2019-10172"],
    },
    {
      id: 20,
      category: "JSON",
      name: "Gson",
      oldCoord: "com.google.code.gson:gson:2.3",
      newCoord: "com.google.code.gson:gson:2.11.0",
      oldVersion: "2.3",
      newVersion: "2.11.0",
      status: "minor",
      reason: "Security patches, Java records support.",
      breaking: false,
      cveIds: [],
    },
    {
      id: 21,
      category: "Messaging",
      name: "RabbitMQ Client",
      oldCoord: "com.mig33:mig33rabbitmq-client:0.5.0",
      newCoord: "com.rabbitmq:amqp-client:5.21.0",
      oldVersion: "0.5.0 (private fork)",
      newVersion: "5.21.0",
      status: "major",
      reason: "Private fork replaced with official RabbitMQ Java client.",
      breaking: true,
      cveIds: [],
    },
    {
      id: 22,
      category: "Distributed",
      name: "Hazelcast",
      oldCoord: "com.hazelcast:hazelcast:3.0.2",
      newCoord: "com.hazelcast:hazelcast:5.4.0",
      oldVersion: "3.0.2",
      newVersion: "5.4.0",
      status: "major",
      reason: "10+ year gap; major API redesign. New CP subsystem, split-brain protection.",
      breaking: true,
      cveIds: [],
    },
    {
      id: 23,
      category: "SSH",
      name: "JSch",
      oldCoord: "com.jcraft:jsch:0.1.33",
      newCoord: "com.github.mwiede:jsch:0.2.21",
      oldVersion: "0.1.33",
      newVersion: "0.2.21",
      status: "major",
      reason: "Original jcraft fork abandoned. mwiede fork is actively maintained with modern algorithms.",
      breaking: false,
      cveIds: ["CVE-2016-5725"],
    },
    {
      id: 24,
      category: "XMPP",
      name: "Smack",
      oldCoord: "jivesoftware:smack:3.1.0.1",
      newCoord: "org.igniterealtime.smack:smack-core:4.4.8",
      oldVersion: "3.1.0.1",
      newVersion: "4.4.8",
      status: "major",
      reason: "New Maven coordinates; major API rework; XEP coverage improved.",
      breaking: true,
      cveIds: [],
    },
    {
      id: 25,
      category: "HTTP",
      name: "Apache HttpClient",
      oldCoord: "org.apache.httpcomponents:httpcore:4.1",
      newCoord: "org.apache.httpcomponents.client5:httpclient5:5.x",
      oldVersion: "4.1",
      newVersion: "5.x",
      status: "major",
      reason: "HttpClient 5 is async-first, HTTP/2 ready, new fluent API.",
      breaking: true,
      cveIds: [],
    },
    {
      id: 26,
      category: "Utilities",
      name: "Guava",
      oldCoord: "com.google.guava:guava:16.0.1",
      newCoord: "com.google.guava:guava:33.2.1-jre",
      oldVersion: "16.0.1",
      newVersion: "33.2.1-jre",
      status: "minor",
      reason: "Many deprecated APIs removed; use JDK equivalents where available.",
      breaking: false,
      cveIds: [],
    },
    {
      id: 27,
      category: "Utilities",
      name: "Commons Lang",
      oldCoord: "commons-lang:commons-lang:2.4 + org.apache.commons:commons-lang3:3.1",
      newCoord: "org.apache.commons:commons-lang3:3.14.0",
      oldVersion: "2.4 + 3.1",
      newVersion: "3.14.0 (consolidated)",
      status: "minor",
      reason: "commons-lang 2.x is deprecated. Consolidated to single commons-lang3.",
      breaking: false,
      cveIds: [],
    },
    {
      id: 28,
      category: "Utilities",
      name: "Commons Codec",
      oldCoord: "commons-codec:commons-codec:1.3",
      newCoord: "commons-codec:commons-codec:1.17.0",
      oldVersion: "1.3",
      newVersion: "1.17.0",
      status: "minor",
      reason: "Constant-time string comparison fixes, new encoders.",
      breaking: false,
      cveIds: [],
    },
    {
      id: 29,
      category: "Utilities",
      name: "Commons CLI",
      oldCoord: "commons-cli:commons-cli:1.0",
      newCoord: "commons-cli:commons-cli:1.9.0",
      oldVersion: "1.0",
      newVersion: "1.9.0",
      status: "minor",
      reason: "Feature-rich API; fluent builder; 20 year gap.",
      breaking: false,
      cveIds: [],
    },
    {
      id: 30,
      category: "Utilities",
      name: "Commons Collections",
      oldCoord: "commons-collections:commons-collections:3.2",
      newCoord: "org.apache.commons:commons-collections4:4.4",
      oldVersion: "3.2",
      newVersion: "4.4",
      status: "major",
      reason: "CVE-2015-6420 deserialization RCE on v3. Collections4 has new Maven coords.",
      breaking: true,
      cveIds: ["CVE-2015-6420"],
    },
    {
      id: 31,
      category: "Testing",
      name: "JUnit",
      oldCoord: "junit:junit:3.8.1",
      newCoord: "org.junit.jupiter:junit-jupiter (JUnit 5)",
      oldVersion: "3.8.1",
      newVersion: "5.11.x",
      status: "major",
      reason: "JUnit 3 requires class inheritance. JUnit 5 uses annotations and extensions.",
      breaking: true,
      cveIds: [],
    },
    {
      id: 32,
      category: "Testing",
      name: "TestNG",
      oldCoord: "org.testng:testng:6.1.1",
      newCoord: "org.testng:testng:7.10.2",
      oldVersion: "6.1.1",
      newVersion: "7.10.2",
      status: "minor",
      reason: "Java 11+ baseline; updated XML config format.",
      breaking: false,
      cveIds: [],
    },
    {
      id: 33,
      category: "Middleware",
      name: "ICE Middleware",
      oldCoord: "com.zeroc.{mac,linux}:Ice:3.3.1",
      newCoord: "→ Removed (evaluate gRPC as modern alternative)",
      oldVersion: "3.3.1",
      newVersion: "Removed",
      status: "removed",
      reason: "ZeroC ICE middleware removed. Recommend migrating to gRPC or Spring WebFlux.",
      breaking: true,
      cveIds: [],
    },
    {
      id: 34,
      category: "Middleware",
      name: "Xalan XSLT",
      oldCoord: "xalan:xalan:2.7.0",
      newCoord: "→ Removed (built into JDK 11+)",
      oldVersion: "2.7.0",
      newVersion: "Removed",
      status: "removed",
      reason: "Java 11+ includes a modern XSLT implementation. Separate xalan.jar is unnecessary.",
      breaking: false,
      cveIds: [],
    },
    {
      id: 35,
      category: "Middleware",
      name: "SWT",
      oldCoord: "swt:swt-linux/macosx:3.3.1.1",
      newCoord: "→ Removed (server-side app has no GUI)",
      oldVersion: "3.3.1.1",
      newVersion: "Removed",
      status: "removed",
      reason: "Eclipse SWT is a desktop widget toolkit. Not appropriate for a server-side service.",
      breaking: false,
      cveIds: [],
    },
    {
      id: 36,
      category: "Middleware",
      name: "jpcap",
      oldCoord: "jpcap:jpcap:0.7",
      newCoord: "→ Removed (native lib, not on Maven Central)",
      oldVersion: "0.7",
      newVersion: "Removed",
      status: "removed",
      reason: "Low-level packet capture library unavailable on Maven Central; evaluate pcap4j instead.",
      breaking: false,
      cveIds: [],
    },
    {
      id: 37,
      category: "Security",
      name: "Keyczar",
      oldCoord: "org:keyczar:0.6b-1.5-111908",
      newCoord: "→ Removed (use Spring Security Crypto or Tink)",
      oldVersion: "0.6b-1.5",
      newVersion: "Removed",
      status: "removed",
      reason: "Keyczar is deprecated and unmaintained since 2016. Use Spring Security Crypto or Google Tink.",
      breaking: true,
      cveIds: [],
    },
    {
      id: 38,
      category: "Scheduling",
      name: "Quartz",
      oldCoord: "org:quartz:1.6.5",
      newCoord: "org.springframework.boot:spring-boot-starter-quartz (2.3.2)",
      oldVersion: "1.6.5",
      newVersion: "2.3.2 (via Boot starter)",
      status: "major",
      reason: "Spring Boot Quartz starter handles configuration and lifecycle management.",
      breaking: false,
      cveIds: [],
    },
    {
      id: 39,
      category: "Compression",
      name: "compress-lzf",
      oldCoord: "com.ning:compress-lzf:0.9.8:jdk15",
      newCoord: "com.ning:compress-lzf:1.1.2",
      oldVersion: "0.9.8-jdk15",
      newVersion: "1.1.2",
      status: "minor",
      reason: "Drop jdk15 classifier; Java 8+ baseline.",
      breaking: false,
      cveIds: [],
    },
    {
      id: 40,
      category: "Big Data",
      name: "Hive JDBC",
      oldCoord: "org.apache.hive:hive-jdbc:0.12.0-cdh5.1.0",
      newCoord: "org.apache.hive:hive-jdbc:4.0.0",
      oldVersion: "0.12.0-cdh5.1.0",
      newVersion: "4.0.0",
      status: "major",
      reason: "CDH-specific artifact removed. Use upstream Apache Hive 4.",
      breaking: false,
      cveIds: [],
    },
    {
      id: 41,
      category: "Big Data",
      name: "Hadoop Common",
      oldCoord: "org.apache.hadoop:hadoop-common:2.5.1",
      newCoord: "org.apache.hadoop:hadoop-common:3.4.0",
      oldVersion: "2.5.1",
      newVersion: "3.4.0",
      status: "minor",
      reason: "Hadoop 3.x is Java 8+, improved YARN, and active security fixes.",
      breaking: false,
      cveIds: [],
    },
    {
      id: 42,
      category: "Build",
      name: "Maven Compiler Plugin",
      oldCoord: "maven-compiler-plugin:2.3.2 (source=1.5, target=1.5)",
      newCoord: "maven-compiler-plugin:3.13.0 (release=21)",
      oldVersion: "2.3.2 (Java 1.5)",
      newVersion: "3.13.0 (Java 21)",
      status: "critical",
      reason: "Compile target bumped from Java 1.5 to Java 21. Enables records, pattern matching, sealed classes.",
      breaking: true,
      cveIds: [],
    },
  ],
  codeChanges: [
    {
      file: "com/projectgoth/fusion/common/Redis.java",
      changes: [
        "Replace `import org.apache.log4j.Logger` with `import org.slf4j.Logger; import org.slf4j.LoggerFactory`",
        "Replace `Logger.getLogger(...)` with `LoggerFactory.getLogger(...)`",
        "Jedis 5 API: `JedisPool` constructor args changed; update config",
        "Use try-with-resources for Jedis connections (Java 7+ feature)",
      ],
      effort: "Medium",
    },
    {
      file: "com/projectgoth/fusion/common/StringUtil.java",
      changes: [
        "Replace `import org.apache.log4j.Logger` → SLF4J",
        "`StringEscapeUtils` moved to commons-text in commons-lang3 3.6+; update import",
        "Replace raw `Iterator` loops with enhanced for-loops or Streams",
        "`new HashMap()` → `new HashMap<>()` (diamond inference, Java 7+)",
      ],
      effort: "Low",
    },
    {
      file: "com/projectgoth/fusion/authentication/AuthenticationService.java",
      changes: [
        "Remove ICE middleware imports (`Ice.Application`, `Ice.ObjectAdapter`, `Ice.Util`)",
        "Replace ICE `Application` base class with Spring Boot `@SpringBootApplication` entry point",
        "Replace log4j imports with SLF4J",
        "Replace `@Required` Spring annotation (deprecated in Spring 5.1) with constructor injection",
      ],
      effort: "High",
    },
    {
      file: "com/projectgoth/fusion/common/HashUtils.java",
      changes: [
        "Replace `input.getBytes(\"ISO8859_1\")` with `input.getBytes(StandardCharsets.ISO_8859_1)` for type safety",
        "Use multi-catch: `catch (NoSuchAlgorithmException | UnsupportedEncodingException e)`",
        "Consider using `java.security.MessageDigest` factory via `getInstance()` – no import changes needed",
      ],
      effort: "Low",
    },
    {
      file: "All EJB files (com/projectgoth/fusion/ejb/**)",
      changes: [
        "Remove XDoclet annotations (`@ejb.bean`, `@ejb.transaction`, etc.)",
        "Remove EJB 2.0 interfaces (`javax.ejb.EJBLocalObject`, `SessionBean`, etc.)",
        "Convert stateless session beans to Spring `@Service` components",
        "Move descriptor from `ejb-jar.xml` / `jboss.xml` to Spring bean definitions",
      ],
      effort: "High",
    },
    {
      file: "All *.java using javax.* APIs",
      changes: [
        "Global rename: `javax.servlet` → `jakarta.servlet`",
        "Global rename: `javax.mail` → `jakarta.mail`",
        "Global rename: `javax.xml.bind` → `jakarta.xml.bind`",
        "Global rename: `javax.ws.rs` → `jakarta.ws.rs`",
      ],
      effort: "Medium (automated via sed / IntelliJ migration wizard)",
    },
  ],
  removedPlugins: [
    {
      plugin: "org.codehaus.mojo:xdoclet-maven-plugin:1.0",
      reason: "XDoclet is obsolete; EJB 3 uses standard Java annotations",
    },
    {
      plugin: "com.google.code.maven-replacer-plugin:replacer:1.5.2",
      reason: "Replaced with maven-resources-plugin filtering",
    },
    {
      plugin: "slice2java (ICE code generator)",
      reason: "ICE middleware removed from project",
    },
    {
      plugin: "openejb-jar-gen Python script",
      reason: "OpenEJB replaced by Spring container",
    },
  ],
  addedPlugins: [
    {
      plugin: "org.springframework.boot:spring-boot-maven-plugin",
      reason: "Creates executable fat-JAR and Docker layer metadata",
    },
    {
      plugin: "org.owasp:dependency-check-maven:10.0.3",
      reason: "Automatically scans dependencies for known CVEs (OWASP NVD)",
    },
    {
      plugin: "org.codehaus.mojo:versions-maven-plugin:2.17.1",
      reason: "Reports available dependency updates (mvn versions:display-dependency-updates)",
    },
  ],
};

export async function registerRoutes(
  httpServer: Server,
  app: Express
): Promise<Server> {

  app.get("/api/analysis", (_req, res) => {
    res.json(DEPENDENCY_DATA);
  });

  app.get("/api/analysis/summary", (_req, res) => {
    res.json({
      projectInfo: DEPENDENCY_DATA.projectInfo,
      summary: DEPENDENCY_DATA.summary,
    });
  });

  app.get("/api/analysis/dependencies", (_req, res) => {
    const { category, status } = _req.query as Record<string, string>;
    let deps = DEPENDENCY_DATA.dependencies;
    if (category && category !== "all") {
      deps = deps.filter((d) => d.category.toLowerCase() === category.toLowerCase());
    }
    if (status && status !== "all") {
      deps = deps.filter((d) => d.status === status);
    }
    res.json(deps);
  });

  app.get("/api/analysis/code-changes", (_req, res) => {
    res.json(DEPENDENCY_DATA.codeChanges);
  });

  app.get("/api/analysis/plugins", (_req, res) => {
    res.json({
      removed: DEPENDENCY_DATA.removedPlugins,
      added: DEPENDENCY_DATA.addedPlugins,
    });
  });

  return httpServer;
}
